export default {
  ADD_NEW_TASK: "ADD_NEW_TASK",
  DELETE_TASK: "DELETE_TASK",
  EDIT_TASK: "EDIT_TASK",
  HANDLE_ERROR: "HANDLE_ERROR",
  SHOW_MODAL: "SHOW_MODAL",
  CHANGE_COMPLETED: "CHANGE_COMPLETED",
  FILTER_TASKS: "FILTER_TASKS",
  CREATE_TASK_BTN: "createTaskBtn",
  HIDE_MODAL_BTN: "hideModalBtn",
};
